In [12]:
# Import dependencies
import pandas as pd
from pathlib import Path
import os

In [13]:
# Store filepath in a variable and the data into a Pandas DataFrame
csv_path = Path("Resources/heart_attack_prediction_dataset.csv")
heart_df = pd.read_csv(csv_path)
heart_df.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [14]:
# Rename Columns
heart_clean_df = heart_df.rename(columns = {"Patient ID": "Patient_ID", 
                                            "Blood Pressure": "Blood_Pressure",
                                            "Heart Rate": "Heart_Rate",
                                            "Family History": "Family_History",
                                            "Alcohol Consumption": "Alcohol_Consumption",
                                            "Exercise Hours Per Week": "Exercise_Hours_Per_Week",
                                            "Previous Heart Problems": "Previous_Heart_Problems",
                                            "Medication Use": "Medication_Use",
                                            "Stress Level": "Stress_Level",
                                            "Sedentary Hours Per Day": "Sedentary_Hours_Per_Day",
                                           "Physical Activity Days Per Week": "Physical_Activity_Days_Per_Week",
                                            "Sleep Hours Per Day": "Sleep_Hours_Per_Day",
                                            "Heart Attack Risk": "Heart_Attack_Risk"})
heart_clean_df.head()

,Patient_ID,Age,Sex,Cholesterol,Blood_Pressure,Heart_Rate,Diabetes,Family_History,Smoking,Obesity,...,Sedentary_Hours_Per_Day,Income,BMI,Triglycerides,Physical_Activity_Days_Per_Week,Sleep_Hours_Per_Day,Country,Continent,Hemisphere,Heart_Attack_Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [15]:
heart_clean_df.to_csv('Resources/heart_clean_df.csv')